package com.hand.dao;

import org.apache.ibatis.annotations.Param;

import com.hand.model.Admin;

/**
 * 
 * @author wangdong
 * @since 2017/07/07
 *
 */
public interface AdminDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated
     */
    Admin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Admin record);
    
    /**
     * 管理员登录
     * @param admin_name
     * @param pwd
     * @return
     */
    int adminLogin(@Param("admin_name") String admin_name,@Param("pwd") String pwd);
    
}