package com.hand.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hand.model.User;

/**
 * 
 * @author wangdong
 * @since 2017/07/07
 *
 */
public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 用户登录
     * @param name
     * @param pwd
     * @return
     */
    int userLogin(@Param("name") String name,@Param("pwd") String pwd);
    
    /**
     * 用户列表
     * @return
     */
    List<User> userList();
    
    /**
     * 根据用户名查询用户
     * @param name
     * @return
     */
    List<User> findUserByName(@Param("name") String name);
    
    /** 
     * 使用注解方式传入多个参数，用户产品分页，通过登录用户ID查询 
     * @param page 
     * @param userId 
     * @return startPos},#{pageSize}  
     */  
    List<User> selectProductsByPage(@Param(value="startPos") Integer startPos,@Param(value="pageSize") Integer pageSize);  
      
    /** 
     * 取得产品数量信息，通过登录用户ID查询 
     * @param userId 
     * @return 
     */  
    long getProductsCount();
}